export const ADD_PROBLEM = 'ADD_PROBLEM';

export const TOGGLE_SHOW_LEFT_DRAWER = 'TOGGLE_SHOW_LEFT_DRAWER';
export const TOGGLE_SHOW_BOTTOM_DRAWER = 'TOGGLE_SHOW_BOTTOM_DRAWER';

export const UPDATE_SEARCH_STRING = 'UPDATE_SEARCH_STRING';